language: node_js
node_js:
  - "6.0"
before_script:
  - npm i -g typescript tsd tslint
  - tsd install
script:
  - tsc
  - npm run tslint
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  except:
    - release
