language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g gulp typescript tsd
  - tsd install
script:
  - tsc && gulp tslint
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
